repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: no-commit-to-branch
  - id: check-added-large-files
- repo: https://github.com/kynan/nbstripout
  rev: 0.3.9
  hooks:
  - id: nbstripout
    files: ".ipynb"
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.6.0
  hooks:
  - id: nbqa-black
    additional_dependencies: [black==20.8b1]
    args: [--nbqa-mutate]
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: notebooks/OLD/|src/OLD/|tests/OLD/
        args: [--max-line-length=88, --max-complexity=10, "--ignore=W503,E203"]
