name: Pulumi Preview
on:
  pull_request:
    branches:
      - main
env:
  AWS_ROLE_TO_ASSUME: arn:aws:iam::189157455002:role/github-actions-infrastructure
  DATA_ROLE: arn:aws:iam::593291632749:role/restricted-admin
jobs:
  preview-stack:
    name: Preview Stack
    runs-on: [self-hosted, management-infrastructure]
    strategy:
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Upgrade AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
      - name: Configure root AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Configure data AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ env.DATA_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Remove existing Pulumi installations
        run: |
          rm -rf $HOME/.pulumi
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
        with:
          pulumi-version: ^3.0.0
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --upgrade -r requirements.txt; fi
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: data-engineering-exports